export const todo: string;
export const saving: string;
export const overdue: string;
export const description: string;
export const descriptionContainer: string;
export const details: string;
export const extra: string;
export const dueDate: string;
export const dueDateInput: string;
